clickhouse:
  # 集群节点列表
  nodes:
    - host: "clickhouse-server"  # ClickHouse服务器主机名
      port: 9000                 # 默认ClickHouse TCP端口

  # 基本连接配置
  database: "default"            # 数据库名称
  username: "default"            # 用户名
  password: ""                   # 密码
  debug: true                    # 是否启用调试日志
  cluster_name: "clickhouse_cluster"  # 集群名称

  # 连接池配置
  max_idle_conns: 5              # 最大空闲连接数
  max_open_conns: 20             # 最大打开连接数
  conn_max_lifetime: 3600s       # 连接最大生命周期(1小时)

  # 超时设置
  dial_timeout: 10s              # 连接超时
  read_timeout: 30s              # 读取超时